### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by eiherrera** [egromero/T07#11]
Tengo el error NameError: name 'lsd' is not defined

**Comment by egromero** [comment]
Intentaste con esto?: https://www.bing.com/cr?IG=7EC1DCFEC252416E93262905CFE71E07&CID=09D997F901E9604E249C9D4E00EF610B&rd=1&h=XiWgu2KarWVT2DQYr5F9k1pvsIC_DfIlM-81pkBdsGw&v=1&r=https%3a%2f%2fstackoverflow.com%2fquestions%2f14804084%2fpython-nameerror-name-is-not-defined&p=DevEx,5071.1

 Saludos @metalbass_bot
