### ISSUE TITLE
Issue hecha desde otro usuario

### ISSUE THREAD

**Issue by Eg-rs** [egromero/T07#4]
Tengo el error NameError: name 'lsd' is not defined

**Comment by egromero** [comment]
Intentaste con esto?: https://www.bing.com/cr?IG=C733F8B49C0D43BABF0905F3BE1A99CE&CID=36EE7366229761B7032B79CB23916030&rd=1&h=9hIFpFn2OQdq9DDN6J612m4rVU2Ux93wrXFCO-1nutA&v=1&r=https%3a%2f%2fen.wikipedia.org%2fwiki%2fLsd&p=DevEx,5074.1

 Saludos @metalbass_bot

**Comment by Eg-rs** [comment]
Gracias!

**Comment by ifcarrera** [comment]
servirá si pongo token en ve de credenciales ?
