### ISSUE TITLE
Test Cerrar sin etiqueta gogleable

### ISSUE THREAD

**Issue by egromero** [egromero/T07#5]
En este test, hay otro usuario involucrado, por lo que no puede poner la etiqueta cuando la cierren
NameError: name 'lasd' is not defined

**Comment by egromero** [comment]
Intentaste con esto?: https://www.bing.com/cr?IG=1385ECEC52F04A94B1444B7F35D1EDB0&CID=3D92B9F55C516451039DB3585D5765BA&rd=1&h=xQddjqedFIzvQE2Zu1hpHomhVz3or11E5ld5ELx9Oy0&v=1&r=https%3a%2f%2fen.wikipedia.org%2fwiki%2fLos_Angeles_County_Sheriff%2527s_Department&p=DevEx,5075.1

 Saludos @metalbass_bot

**Comment by Eg-rs** [comment]
Pero tambien podrías hacer esto "bla bla"
