### ISSUE TITLE
Prueba nº2 correcion link

### ISSUE THREAD

**Issue by egromero** [egromero/T07#8]
Tengo el error NameError: name 'lsd' is not defined

**Comment by egromero** [comment]
Para el error  name 'lsd' is not d Intentaste con esto?: http://www.bing.com/cr?IG=FB7B1CE21EC743588E74103A6CEF5BF7&CID=02CFCEEA40F667310207C44741F066EF&rd=1&h=oLjprGYu-SDCS-FGmbSFDItFVItvGUD0TOSD48GN-ME&v=1&r=http%3a%2f%2fstackoverflow.com%2fquestions%2f24062830%2fbest-way-to-package-a-python-library-that-includes-a-c-shared-library&p=DevEx,5072.1

 Saludos @metalbass_bot

**Comment by eiherrera** [comment]
hola
